Feature/20 header footer static
scuoleparrocchialidesio/www pull request #35
Opened 2019-04-09 16:58 UTC by EnigmaEdivad

2019-04-10 07:24 UTC, olistik requested changes
Nel layout ci sono due `<body />`.

2019-04-10 18:03 UTC, olistik commented
Mi riferivo al tag body, comprensivo della doppia apertura.

2019-04-12 09:14 UTC, EnigmaEdivad commented
Così?

2019-04-12 09:15 UTC, olistik commented
@EnigmaEdivad Manca solo da sistemare l'indentazione di tutto il body. 😅

2019-04-12 10:47 UTC, olistik approved these changes

2019-04-12 11:22 UTC, merged