27 esploratory
scuoleparrocchialidesio/www pull request #57
Opened 2019-07-26 16:45 UTC by EnigmaEdivad

2019-07-26 16:47 UTC, olistik requested changes

2019-07-26 16:47 UTC, olistik commented on source/esploratori.html.erb
> +        <%= link_to 'Scopri', "/esploraoti.html", class:'button button--card-action' %>
Typo: il link dovrebbe essere `/esploratori.html`.

2019-07-26 17:41 UTC, EnigmaEdivad commented on source/esploratori.html.erb
> +        <%= link_to 'Scopri', "/esploraoti.html", class:'button button--card-action' %>
OK

2019-07-29 07:31 UTC, olistik requested changes

2019-07-29 07:31 UTC, olistik commented on source/esploratori.html.erb
> +      <h1 class="section-card__title font-title">Calentario</h1>
Typo: `Calentario` -> `Calendario`.

2019-07-29 07:32 UTC, EnigmaEdivad commented on source/esploratori.html.erb
> +      <h1 class="section-card__title font-title">Calentario</h1>
Cavoli...

2019-07-29 07:33 UTC, olistik approved these changes

2019-07-29 07:36 UTC, merged